language: python

jobs:
  include:
    # We have a primary stage that runs the basic sanity checks
    - stage: primary
      env: TOXENV=docs
    - env: TOXENV=packaging
    - env: TOXENV=mypy
    - env: TOXENV=lint-py3
    - env: TOXENV=lint-py2
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py27
      python: 2.7

    # We have a secondary stage that runs the additional checks
    - stage: secondary
      env: TOXENV=pypy
      python: pypy3
    - env: TOXENV=pypy
      python: pypy
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py34
      python: 3.4

  allow_failures:
    - python: nightly

install:
  - travis_retry tools/travis/install.sh
script:
  - tox
